# Generated by Django 6.1.1 on 2026-09-28 02:04

import django.db.models.deletion
import profissionais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, upload_to=profissionais.models.foto_path)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['nome', 'pk'],
                'indexes': [models.Index(fields=['tenant', 'ativo'], name='prof_tenant_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('id', 'tenant'), name='prof_id_tenant_unique')],
            },
        ),
    ]
