# Generated by Django 6.1.1 on 2026-10-10 21:13

import profissionais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto_fundo',
            field=models.ImageField(blank=True, upload_to=profissionais.models.foto_fundo_path, verbose_name='Foto de fundo'),
        ),
    ]
