# Generated by Django 6.1.1 on 2026-09-30 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_remove_payment_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias', models.PositiveSmallIntegerField(default=30)),
                ('producao', models.BooleanField(default=False)),
                ('preferencia_id', models.CharField(blank=True, max_length=200)),
                ('recebedor_id', models.CharField(blank=True, max_length=100)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('retorno_url', models.URLField(max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_acesso', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoAcesso',
            fields=[
                ('payment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('creditado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.checkoutacesso')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkoutacesso',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='checkout_acesso_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='checkoutacesso',
            constraint=models.CheckConstraint(condition=models.Q(('dias', 30)), name='checkout_acesso_trinta_dias'),
        ),
    ]
