# Generated by Django 6.1.1 on 2026-09-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('evento', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('recebida', 'Recebida'), ('processada', 'Processada'), ('aguardando_reenvio', 'Aguardando reenvio'), ('sem_correspondencia', 'Sem correspondência'), ('ignorada', 'Ignorada')], default='recebida', max_length=24)),
                ('dado_bruto', models.TextField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_mercado_pago', to='pagamentos.pagamentoacesso')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
    ]
