# Generated by Django 6.1.1 on 2026-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_notificacaomercadopago'),
        ('tenants', '0012_tenant_plano_tenant_tenant_plano_valido'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutacesso',
            name='plano',
            field=models.CharField(choices=[('INDIVIDUAL', 'Plano Individual'), ('ILIMITADO', 'Plano Profissional')], default='INDIVIDUAL', max_length=10),
        ),
        migrations.AddConstraint(model_name='checkoutacesso', constraint=models.CheckConstraint(condition=models.Q(plano__in=['INDIVIDUAL', 'ILIMITADO']), name='checkout_acesso_plano_valido')),
    ]
