# Generated by Django 6.1.1 on 2026-10-06 19:56

from django.db import migrations, models


def atualizar_planos(apps, schema_editor):
    apps.get_model('pagamentos', 'CheckoutAcesso').objects.using(schema_editor.connection.alias).filter(plano='ILIMITADO').update(plano='PROFISSIONAL')
    # Historical expiry snapshots cannot be reconstructed reliably.
    Payment = apps.get_model('pagamentos', 'PagamentoAcesso')
    for payment in Payment.objects.using(schema_editor.connection.alias).filter(creditado_em__isnull=False).select_related('checkout').iterator():
        payment.aprovado_em = payment.creditado_em
        payment.dias_concedidos = payment.checkout.dias
        payment.save(update_fields=['aprovado_em', 'dias_concedidos'])


def reverter_planos(apps, schema_editor):
    apps.get_model('pagamentos', 'CheckoutAcesso').objects.using(schema_editor.connection.alias).filter(plano='PROFISSIONAL').update(plano='ILIMITADO')


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_checkoutacesso_plano'),
        ('tenants', '0014_remove_tenant_tenant_plano_valido_alter_tenant_plano_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkoutacesso',
            name='checkout_acesso_plano_valido',
        ),
        migrations.AddField(
            model_name='pagamentoacesso',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentoacesso',
            name='dias_concedidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagamentoacesso',
            name='nova_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentoacesso',
            name='validade_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutacesso',
            name='plano',
            field=models.CharField(choices=[('INDIVIDUAL', 'Plano Individual'), ('PROFISSIONAL', 'Plano Profissional')], default='INDIVIDUAL', max_length=12),
        ),
        migrations.RunPython(atualizar_planos, reverter_planos),
        migrations.AddConstraint(
            model_name='checkoutacesso',
            constraint=models.CheckConstraint(condition=models.Q(('plano__in', ['INDIVIDUAL', 'PROFISSIONAL'])), name='checkout_acesso_plano_valido'),
        ),
    ]
