# Generated by Django 6.1.1 on 2026-09-28 02:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duracao_minutos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='profissionais.profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='catalogo.servico')),
            ],
            options={
                'ordering': ['servico__nome', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['tenant', 'ativo'], name='servico_tenant_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='servico_id_tenant_unique'),
        ),
        migrations.AddIndex(
            model_name='profissionalservico',
            index=models.Index(fields=['tenant', 'servico', 'ativo'], name='ps_tenant_servico_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.UniqueConstraint(fields=('tenant', 'profissional', 'servico'), name='prof_servico_tenant_unique'),
        ),
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='prof_servico_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_minutos__gt', 0)), name='prof_servico_duracao_positiva'),
        ),
    ]
