# Generated by Django 6.1.1 on 2026-09-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_tenant_foreign_keys'),
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.UniqueConstraint(fields=('id', 'tenant', 'profissional'), name='ps_id_tenant_prof_unique'),
        ),
    ]
