# Generated by Django 6.1.1 on 2026-09-28 02:04

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades', to='profissionais.profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['data', 'hora_inicio', 'pk'],
                'indexes': [models.Index(fields=['tenant', 'profissional', 'data'], name='disp_tenant_prof_data_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='disp_inicio_antes_fim'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('ativo', True)), expressions=[('tenant', '='), ('profissional', '='), (models.Func(models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('data'), '+', models.F('hora_inicio')), output_field=models.DateTimeField()), models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('data'), '+', models.F('hora_fim')), output_field=models.DateTimeField()), models.Value('[)'), function='TSRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='disp_sem_sobreposicao', violation_error_message='Já existe um período ativo sobreposto para este profissional nesta data.')],
            },
        ),
    ]
