# Generated by Django 6.1.1 on 2026-09-28 17:16

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_tenant_foreign_key'),
        ('catalogo', '0002_tenant_foreign_keys'),
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150)),
                ('servico_nome', models.CharField(max_length=150)),
                ('profissional_nome', models.CharField(max_length=150)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='catalogo.profissionalservico')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='profissionais.profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['inicio', 'pk'],
                'indexes': [models.Index(fields=['tenant', 'cliente', 'inicio'], name='ag_cliente_inicio_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('inicio__lt', models.F('fim'))), name='ag_inicio_antes_fim'), models.CheckConstraint(condition=models.Q(('duracao_minutos__gt', 0), ('valor__gt', 0)), name='ag_valor_duracao_positivos'), models.CheckConstraint(condition=models.Q(models.Q(('cancelado_em__isnull', True), ('status', 'CONFIRMADO')), models.Q(('cancelado_em__isnull', False), ('status', 'CANCELADO')), _connector='OR'), name='ag_status_consistente'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'CONFIRMADO')), expressions=[('tenant', '='), ('profissional', '='), (models.Func('inicio', 'fim', models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='ag_sem_sobreposicao', violation_error_message='Esse horário já está reservado.')],
            },
        ),
    ]
