# Generated by Django 6.1.1 on 2026-09-28 18:32

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_booking_integrity'),
        ('catalogo', '0003_profissionalservico_ps_id_tenant_prof_unique'),
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='ag_status_consistente',
        ),
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='ag_sem_sobreposicao',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nao_compareceu_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não compareceu')], default='CONFIRMADO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelado_em__isnull', True), ('nao_compareceu_em__isnull', True), ('status', 'CONFIRMADO')), models.Q(('cancelado_em__isnull', False), ('nao_compareceu_em__isnull', True), ('status', 'CANCELADO')), models.Q(('cancelado_em__isnull', True), ('nao_compareceu_em__isnull', False), ('status', 'NAO_COMPARECEU')), _connector='OR'), name='ag_status_consistente'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['CONFIRMADO', 'NAO_COMPARECEU'])), expressions=[('tenant', '='), ('profissional', '='), (models.Func('inicio', 'fim', models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='ag_sem_sobreposicao', violation_error_message='Esse horário já está reservado.'),
        ),
    ]
