# Generated by Django 6.1.1 on 2026-09-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_agendamento_ag_status_consistente_and_more'),
        ('catalogo', '0003_profissionalservico_ps_id_tenant_prof_unique'),
        ('profissionais', '0001_initial'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
        ('usuarios', '0007_contatocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='usuarios.contatocliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('contato__isnull', True)), models.Q(('cliente__isnull', True), ('contato__isnull', False)), _connector='OR'), name='ag_cliente_ou_contato'),
        ),
    ]
