# Generated by Django 6.1.1 on 2026-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_contato_tenant_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='acesso_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
