# Generated by Django 6.1.1 on 2026-10-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agendamento_cliente_whatsapp'),
        ('catalogo', '0003_profissionalservico_ps_id_tenant_prof_unique'),
        ('profissionais', '0001_initial'),
        ('tenants', '0011_tenant_limite_agendamentos_cliente_futuros'),
        ('usuarios', '0009_whatsappbloqueado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_normalizado', models.CharField(max_length=16)),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('CONCLUIDO', 'Compareceu'), ('ATRASADO', 'Chegou atrasado'), ('DESMARCOU', 'Desmarcou'), ('AUSENTE', 'Cliente ausente')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='ag_id_tenant_unique'),
        ),
        migrations.AddField(
            model_name='reputacaocliente',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacao_reputacao', to='agenda.agendamento'),
        ),
        migrations.AddField(
            model_name='reputacaocliente',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='reputacaocliente',
            index=models.Index(fields=['tenant', 'whatsapp_normalizado'], name='reputacao_tenant_whatsapp_idx'),
        ),
        migrations.AddConstraint(
            model_name='reputacaocliente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pontuacao', 4), ('tipo', 'CONCLUIDO')), models.Q(('pontuacao', 3), ('tipo', 'ATRASADO')), models.Q(('pontuacao', 2), ('tipo', 'DESMARCOU')), models.Q(('pontuacao', 1), ('tipo', 'AUSENTE')), _connector='OR'), name='reputacao_tipo_pontos_validos'),
        ),
        migrations.RunSQL(
            'ALTER TABLE agenda_reputacaocliente ADD CONSTRAINT reputacao_ag_tenant_fk '
            'FOREIGN KEY (agendamento_id, tenant_id) REFERENCES agenda_agendamento (id, tenant_id) DEFERRABLE INITIALLY IMMEDIATE',
            'ALTER TABLE agenda_reputacaocliente DROP CONSTRAINT reputacao_ag_tenant_fk',
        ),
    ]
