# Generated by Django 6.1.1 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_reputacaocliente_agendamento_ag_id_tenant_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='conclusao_confirmada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
