# Generated by Django 6.1.1 on 2026-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_agendamento_conclusao_confirmada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente_whatsapp',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='reputacaocliente',
            name='whatsapp_normalizado',
            field=models.CharField(max_length=40),
        ),
    ]
