# Generated by Django 6.1.1 on 2026-09-28 01:32

import django.core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('subdomain', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$', 'Use um subdomínio de até 63 caracteres: letras minúsculas, números e hífens internos.')])),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, validators=[tenants.models.validate_timezone])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
