# Generated by Django 6.1.1 on 2026-09-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('subdomain__regex', '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')), name='tenant_subdomain_valid'),
        ),
    ]
