# Generated by Django 6.1.1 on 2026-09-28 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenant_subdomain_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='intervalo_grade_minutos',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_grade_minutos__gt', 0)), name='tenant_grade_positiva'),
        ),
    ]
