# Generated by Django 6.1.1 on 2026-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='expira_em',
            field=models.DateField(blank=True, help_text='Validade do acesso do estabelecimento. Em branco enquanto não houver prazo definido. Este campo não bloqueia o acesso automaticamente.', null=True, verbose_name='Data de expiração'),
        ),
    ]
