# Generated by Django 6.1.1 on 2026-09-29 18:52

from datetime import timedelta
from zoneinfo import ZoneInfo

from django.db import migrations, models


def preencher_expiracao(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    database = schema_editor.connection.alias
    for tenant in Tenant.objects.using(database).filter(expira_em__isnull=True).iterator():
        expiration = tenant.criado_em.astimezone(ZoneInfo(tenant.timezone)).date() + timedelta(days=30)
        Tenant.objects.using(database).filter(pk=tenant.pk, expira_em__isnull=True).update(expira_em=expiration)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_expira_em'),
    ]

    operations = [
        migrations.RunPython(preencher_expiracao, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenant',
            name='expira_em',
            field=models.DateField(blank=True, help_text='Validade do acesso. Quando não informada, será definida como 30 dias após o cadastro.', null=True, verbose_name='Data de expiração'),
        ),
    ]
