# Generated by Django 6.1.1 on 2026-09-29 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_expira_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_assinatura_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_assinatura_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_checkout_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_valor_assinatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PlataformaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_payment_id', models.CharField(max_length=100, unique=True)),
                ('mercado_pago_assinatura_id', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_plataforma', to='tenants.tenant')),
            ],
        ),
    ]
