# Generated by Django 6.1.1 on 2026-09-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_mercado_pago_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_diagnostico',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mercado_pago_ultimo_webhook',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
