# Generated by Django 6.1.1 on 2026-09-30 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_mercado_pago_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preference_id', models.CharField(blank=True, max_length=200)),
                ('collector_id', models.CharField(blank=True, max_length=100)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_plataforma', to='tenants.tenant')),
            ],
        ),
    ]
