# Generated by Django 6.1.1 on 2026-09-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_plataformacheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataformapagamento',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_assinatura_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_assinatura_status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_checkout_url',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_diagnostico',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_idempotency_key',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_ultimo_webhook',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mercado_pago_valor_assinatura',
        ),
        migrations.DeleteModel(
            name='PlataformaCheckout',
        ),
        migrations.DeleteModel(
            name='PlataformaPagamento',
        ),
    ]
