# Generated by Django 6.1.1 on 2026-10-03 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_limite_agendamentos_cliente_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='limite_agendamentos_cliente_futuros',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite de agendamentos futuros por WhatsApp'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('limite_agendamentos_cliente_futuros__gte', 1)), name='tenant_limite_agendamentos_futuros_positivo'),
        ),
    ]