# Generated by Django 6.1.1 on 2026-10-06 18:34

from django.db import migrations, models


def preservar_equipes(apps, schema_editor):
    Profissional = apps.get_model('profissionais', 'Profissional')
    Tenant = apps.get_model('tenants', 'Tenant')
    equipes = Profissional.objects.using(schema_editor.connection.alias).filter(ativo=True).values('tenant_id').annotate(total=models.Count('pk')).filter(total__gt=1)
    Tenant.objects.using(schema_editor.connection.alias).filter(pk__in=equipes.values('tenant_id')).update(plano='ILIMITADO')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_limite_agendamentos_cliente_futuros'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plano',
            field=models.CharField(choices=[('INDIVIDUAL', 'Plano Individual'), ('ILIMITADO', 'Plano Profissional')], default='INDIVIDUAL', max_length=10),
        ),
        migrations.RunPython(preservar_equipes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('plano__in', ['INDIVIDUAL', 'ILIMITADO'])), name='tenant_plano_valido'),
        ),
    ]
