# Generated by Django 6.1.1 on 2026-10-06 19:56

from django.db import migrations, models


def atualizar_planos(apps, schema_editor):
    apps.get_model('tenants', 'Tenant').objects.using(schema_editor.connection.alias).filter(plano='ILIMITADO').update(plano='PROFISSIONAL')


def reverter_planos(apps, schema_editor):
    apps.get_model('tenants', 'Tenant').objects.using(schema_editor.connection.alias).filter(plano='PROFISSIONAL').update(plano='ILIMITADO')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_proteger_limite_profissionais'),
    ]

    operations = [
        migrations.RunSQL('DROP TRIGGER combinado_limite_plano ON tenants_tenant;', 'CREATE TRIGGER combinado_limite_plano BEFORE UPDATE OF plano ON tenants_tenant FOR EACH ROW EXECUTE FUNCTION combinado_limite_plano();'),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='tenant_plano_valido',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plano',
            field=models.CharField(choices=[('INDIVIDUAL', 'Plano Individual'), ('PROFISSIONAL', 'Plano Profissional')], default='INDIVIDUAL', max_length=12),
        ),
        migrations.RunPython(atualizar_planos, reverter_planos),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('plano__in', ['INDIVIDUAL', 'PROFISSIONAL'])), name='tenant_plano_valido'),
        ),
        migrations.RunSQL('CREATE TRIGGER combinado_limite_plano BEFORE UPDATE OF plano ON tenants_tenant FOR EACH ROW EXECUTE FUNCTION combinado_limite_plano();', 'DROP TRIGGER combinado_limite_plano ON tenants_tenant;'),
    ]
