# Generated by Django 6.1.1 on 2026-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_remove_tenant_tenant_plano_valido_alter_tenant_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone de contato'),
        ),
    ]
