# Generated by Django 6.1.1 on 2026-10-07 13:54

from django.db import migrations, models


def copiar_enderecos(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    User = apps.get_model('usuarios', 'User')
    alias = schema_editor.connection.alias
    for tenant in Tenant.objects.using(alias).all().iterator():
        owner = User.objects.using(alias).filter(tenant_id=tenant.pk, tipo='ADMIN').exclude(endereco='').order_by('pk').first()
        if owner:
            endereco = ', '.join(filter(None, [owner.endereco, owner.numero_endereco, owner.bairro,
                ' - '.join(filter(None, [owner.cidade, owner.estado]))]))
            Tenant.objects.using(alias).filter(pk=tenant.pk).update(endereco_publico=endereco)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_razao_social_tenant_telefone'),
        ('usuarios', '0008_user_owner_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='endereco_publico',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Endereço do estabelecimento'),
        ),
        migrations.RunPython(copiar_enderecos, migrations.RunPython.noop),
    ]
