# Generated by Django 6.1.1 on 2026-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_cnpj_tenant_endereco_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefone de contato'),
        ),
    ]
