# Generated by Django 6.1.1 on 2026-09-28 01:34

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def require_review_for_existing_users(apps, schema_editor):
    if apps.get_model("usuarios", "User").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "Existem usuários legados sem tenant. Migração interrompida sem alterar dados: "
            "defina e revise o mapeamento usuário → tenant antes de continuar. "
            "Não atribua automaticamente um tenant padrão."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_tenant_tenant_subdomain_valid'),
        ('usuarios', '0003_remove_cliente_uniq_cliente_tenant_user_and_more'),
    ]

    operations = [
        migrations.RunPython(require_review_for_existing_users, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('PROFISSIONAL', 'Profissional')], default='CLIENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'tipo'], name='user_tenant_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email'))), models.Q(('email', ''), _negated=True)), name='user_email_normalized'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', False), ('tenant__isnull', False)), models.Q(('is_staff', True), ('is_superuser', True), ('tenant__isnull', True), ('tipo', 'ADMIN')), _connector='OR'), name='user_tenant_or_global_superuser'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['ADMIN', 'CLIENTE', 'PROFISSIONAL'])), name='user_tipo_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='user_id_tenant_unique'),
        ),
    ]
