# Generated by Django 6.1.1 on 2026-09-28 18:17

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cliente_tenant_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=16, validators=[usuarios.validators.validate_whatsapp], verbose_name='WhatsApp'),
        ),
    ]
