# Generated by Django 6.1.1 on 2026-09-28 18:50

import django.db.models.deletion
import django.db.models.functions.text
import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
        ('usuarios', '0006_user_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=16, validators=[usuarios.validators.validate_whatsapp])),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('whatsapp'), models.F('tenant'), name='contato_nome_whatsapp_tenant_uniq'), models.UniqueConstraint(fields=('id', 'tenant'), name='contato_id_tenant_unique')],
            },
        ),
    ]
