# Generated by Django 6.1.1 on 2026-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_whatsappbloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatocliente',
            name='whatsapp',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='whatsappbloqueado',
            name='whatsapp',
            field=models.CharField(max_length=40),
        ),
    ]
