# Generated by Django 6.1.1 on 2026-09-28 22:06

import django.core.validators
import django.db.models.deletion
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0007_contato_tenant_integrity'),
        ('tenants', '0003_tenant_intervalo_grade_minutos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Envio iniciado'), ('ENVIADO', 'Aceito pela API'), ('INCERTO', 'Verificar envio')], default='PROCESSANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=250)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembretes_ativos', models.BooleanField(default=False, verbose_name='Ativar lembretes automáticos')),
                ('antecedencia_minutos', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)], verbose_name='Antecedência em minutos')),
                ('mensagem_lembrete', models.TextField(default='Olá, {cliente}! Lembramos do seu agendamento de {servico} com {profissional} em {estabelecimento}, dia {data} às {hora}. Esperamos você!', max_length=2000, validators=[whatsapp.models.validate_message], verbose_name='Mensagem do lembrete')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('antecedencia_minutos__gte', 1), ('antecedencia_minutos__lte', 10080)), name='whatsapp_antecedencia_valida')],
            },
        ),
    ]
