# Generated by Django 6.1.1 on 2026-10-03 17:31

import django.db.models.deletion
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_reputacaocliente_agendamento_ag_id_tenant_unique_and_more'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='confirmacoes_ativas',
            field=models.BooleanField(default=True, verbose_name='Enviar confirmação após o agendamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='mensagem_confirmacao',
            field=models.TextField(default='Olá, {cliente}! Obrigado por agendar com {estabelecimento}. Seu horário para {servico} com {profissional} está confirmado para {data} às {hora}. Aguardamos você no horário combinado! Até lá! 💛', max_length=2000, validators=[whatsapp.models.validate_message], verbose_name='Mensagem de confirmação e agradecimento'),
        ),
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Envio iniciado'), ('ENVIADO', 'Aceito pela API'), ('INCERTO', 'Verificar envio')], default='PROCESSANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=250)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento')),
            ],
        ),
    ]
