# Generated by Django 6.1.1 on 2026-10-03 19:42

import whatsapp.models
from django.db import migrations, models


def atualizar_mensagem_padrao(apps, schema_editor):
    config = apps.get_model('whatsapp', 'Configuracao')
    old = 'Olá, {cliente}! Obrigado por agendar com {estabelecimento}. Seu horário para {servico} com {profissional} está confirmado para {data} às {hora}. Aguardamos você no horário combinado! Até lá! 💛'
    new = 'Olá, {cliente}! Seja bem-vindo(a) a {estabelecimento}! Obrigado pela preferência. Seu horário para {servico} com {profissional} está confirmado para {data} às {hora}. Aguardamos você no horário combinado! Até lá! 💛'
    config.objects.using(schema_editor.connection.alias).filter(mensagem_confirmacao=old).update(mensagem_confirmacao=new)


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_configuracao_confirmacoes_ativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='mensagem_confirmacao',
            field=models.TextField(default='Olá, {cliente}! Seja bem-vindo(a) a {estabelecimento}! Obrigado pela preferência. Seu horário para {servico} com {profissional} está confirmado para {data} às {hora}. Aguardamos você no horário combinado! Até lá! 💛', max_length=2000, validators=[whatsapp.models.validate_message], verbose_name='Mensagem de confirmação e agradecimento'),
        ),
        migrations.RunPython(atualizar_mensagem_padrao, migrations.RunPython.noop),
    ]
