# Generated by Django 6.1.1 on 2026-10-03 22:30

import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_configuracao_mensagem_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='destinatario',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='resposta_api',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='mensagem_confirmacao',
            field=models.TextField(default='Olá, {cliente}! 😊\n\nAgradecemos pela preferência!\n\nSeu horário está reservado para {data} às {horario}, com {profissional}.\n\nServiço: {servico}\n\nAguardamos você no horário combinado.\n\n{empresa}', max_length=2000, validators=[whatsapp.models.validate_message], verbose_name='Mensagem de confirmação e agradecimento'),
        ),
    ]
