# Generated by Django 6.1.1 on 2026-10-06 16:16

import django.db.models.deletion
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_agendamento_conclusao_confirmada_em'),
        ('whatsapp', '0004_confirmacao_destinatario_confirmacao_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='mensagem_retorno',
            field=models.TextField(default='Olá, {nome}! 😊 Já se passaram cerca de 30 dias desde o seu último atendimento. Que tal renovar o visual? Estamos esperando por você! ✂️', max_length=2000, validators=[whatsapp.models.validate_return_message], verbose_name='Mensagem de retorno'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='retornos_ativos',
            field=models.BooleanField(default=False, verbose_name='Enviar lembrete de retorno após 30 dias'),
        ),
        migrations.CreateModel(
            name='LembreteRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(blank=True, max_length=16)),
                ('mensagem', models.TextField(blank=True)),
                ('resposta_api', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Envio iniciado'), ('ENVIADO', 'Aceito pela API'), ('ERRO', 'Falha antes do envio'), ('INCERTO', 'Verificar envio'), ('IGNORADO', 'Não elegível no momento do envio')], default='PROCESSANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tentado_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=250)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lembrete_retorno', to='agenda.agendamento')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('enviado_em__isnull', False), ('status', 'ENVIADO')), models.Q(('enviado_em__isnull', True), ('status__in', ['PROCESSANDO', 'ERRO', 'INCERTO', 'IGNORADO'])), _connector='OR'), name='retorno_status_envio_consistente')],
            },
        ),
    ]
