"""
Django settings for barbe project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Local development overrides; never commit this file.
import json
_local = Path(__file__).resolve().parent.parent / ".local-settings.json"
LOCAL = json.loads(_local.read_text()) if _local.exists() else {}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", LOCAL.get("SECRET_KEY", "django-insecure-local-development-only"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

TENANT_BASE_DOMAIN = os.environ.get("TENANT_BASE_DOMAIN", "localhost").lower()
# Public address used when sharing a store, including from local development.
STORE_BASE_DOMAIN = os.environ.get("STORE_BASE_DOMAIN", "tacombinado.net").strip().lower()
PLATFORM_PUBLIC_URL = os.environ.get('PLATFORM_PUBLIC_URL', f'https://{STORE_BASE_DOMAIN}').strip()
ALLOWED_HOSTS = [TENANT_BASE_DOMAIN, "." + TENANT_BASE_DOMAIN, "localhost", "127.0.0.1", "[::1]"]
DEV_PUBLIC_HOST = os.environ.get('DEV_PUBLIC_HOST', LOCAL.get('DEV_PUBLIC_HOST', '')).strip().lower()
DEV_TENANT_SUBDOMAIN = os.environ.get('DEV_TENANT_SUBDOMAIN', LOCAL.get('DEV_TENANT_SUBDOMAIN', '')).strip().lower()
CSRF_TRUSTED_ORIGINS = []
if DEBUG:
    ALLOWED_HOSTS.append(".localhost")
    if DEV_PUBLIC_HOST:
        ALLOWED_HOSTS.append(DEV_PUBLIC_HOST)
        CSRF_TRUSTED_ORIGINS.append('https://' + DEV_PUBLIC_HOST)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenants',
    'pagamentos',
    'usuarios',
    'django.contrib.postgres',
    'profissionais',
    'catalogo',
    'agenda',
    'painel',
    'whatsapp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'usuarios.seo.SearchIndexMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barbe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barbe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "barbe"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", LOCAL.get("DB_PASSWORD", "")),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = "usuarios.User"
AUTHENTICATION_BACKENDS = ["usuarios.backends.TenantBackend"]
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/conta/"
LOGOUT_REDIRECT_URL = "/login/"
# Host-only cookies: never share authenticated sessions between subdomains.
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise ValueError("Configure DJANGO_SECRET_KEY para produção.")

# Public commercial contact (e.g. https://wa.me/...); never a secret.
PLATFORM_SALES_URL = os.environ.get("PLATFORM_SALES_URL", "")

# Evolution API credentials belong to this deployment, never to browser forms.
EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', LOCAL.get('EVOLUTION_API_URL', ''))
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', LOCAL.get('EVOLUTION_API_KEY', ''))
EVOLUTION_INSTANCE_PREFIX = os.environ.get('EVOLUTION_INSTANCE_PREFIX', 'barbe_tenant')

# Password recovery: Resend SMTP when its API key is configured.
DEFAULT_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', LOCAL.get('RESEND_FROM_EMAIL', os.environ.get('DEFAULT_FROM_EMAIL', 'Tá Combinado <nao-responda@tacombinado.net>')))
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', LOCAL.get('RESEND_API_KEY', ''))
PASSWORD_RESET_TIMEOUT = 3600
if RESEND_API_KEY:
    MAILERS['default'] = {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': 'smtp.resend.com',
            'port': 465,
            'username': 'resend',
            'password': RESEND_API_KEY,
            'use_tls': False,
            'use_ssl': True,
            'timeout': 15,
        },
    }
elif os.environ.get('EMAIL_HOST'):
    MAILERS['default'] = {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': os.environ['EMAIL_HOST'],
            'port': int(os.environ.get('EMAIL_PORT', '587')),
            'username': os.environ.get('EMAIL_HOST_USER', ''),
            'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
            'use_tls': os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true',
            'use_ssl': os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true',
            'timeout': 15,
        },
    }

# Compatibility with the existing configured price; payments are one-off.
PLATFORM_MONTHLY_PRICE = os.environ.get('PLATFORM_MONTHLY_PRICE', LOCAL.get('PLATFORM_MONTHLY_PRICE', '30.00'))
PLATFORM_ACCESS_PRICE = os.environ.get('PLATFORM_ACCESS_PRICE', LOCAL.get('PLATFORM_ACCESS_PRICE', PLATFORM_MONTHLY_PRICE))
MERCADO_PAGO_ACCESS_TOKEN = os.environ.get('MERCADO_PAGO_ACCESS_TOKEN', LOCAL.get('MERCADO_PAGO_ACCESS_TOKEN', '')).strip()
MERCADO_PAGO_WEBHOOK_SECRET = os.environ.get('MERCADO_PAGO_WEBHOOK_SECRET', LOCAL.get('MERCADO_PAGO_WEBHOOK_SECRET', '')).strip()
MERCADO_PAGO_PUBLIC_URL = os.environ.get('MERCADO_PAGO_PUBLIC_URL', LOCAL.get('MERCADO_PAGO_PUBLIC_URL', '')).rstrip('/')
MERCADO_PAGO_LIVE_MODE = str(os.environ.get('MERCADO_PAGO_LIVE_MODE', LOCAL.get('MERCADO_PAGO_LIVE_MODE', 'false'))).lower() == 'true'

# PIN adicional do console de diagnóstico, por sessão de administrador.
WHATSAPP_TESTS_PIN = os.environ.get("WHATSAPP_TESTS_PIN", "1031")

# Exceção de testes restrita ao estabelecimento e número autorizados.
# Formato: subdominio:numero,subdominio:numero. Valor vazio desativa a exceção.
WHATSAPP_TEST_RECIPIENTS = os.environ.get('WHATSAPP_TEST_RECIPIENTS', 'marcos:21990921092')

WHATSAPP_TESTS_DB = Path(os.environ.get("WHATSAPP_TESTS_DB", str(BASE_DIR / "whatsapp-tests.sqlite3")))
